### ISSUE TITLE
Fix `renovate` for `mambaforge-cuda` repository

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/mambaforge-cuda#27]
Previously, the `renovate` bot would open PRs to update our `mambaforge` image versions: https://github.com/rapidsai/mambaforge-cuda/pull/15

However, it seems like this functionality has stopped working.

The current version of `mambaforge` in our image is `22.9.0-2` ([here](https://github.com/rapidsai/mambaforge-cuda/blob/c51ddb0bf44dc3ebe795ab1e0bf2ca84a8ac126a/Dockerfile#L16)) and no PRs have been open by `renovate` despite there being newer versions of `mambaforge` available on DockerHub: https://hub.docker.com/r/condaforge/mambaforge/tags.

We should investigate why this is happening.

`renovate` has a troubleshooting guide here: https://docs.renovatebot.com/troubleshooting/#github-hosted-app.

I've followed their directions to access the logs in the past which has been pretty helpful.

**Comment by jjacobelli** [comment]
Fixed in https://github.com/rapidsai/mambaforge-cuda/commit/d64e63ad88f87677e77d87130275c5508fc2bf07
